5 Number summary code

In [11]:
import numpy as np
arr=np.array([2,3,4,6,7,8,9,12,13,16,17,23,25,27,34,37,201])
print(arr)

[  2   3   4   6   7   8   9  12  13  16  17  23  25  27  34  37 201]


In [12]:
q1=np.percentile(arr,25)
q3=np.percentile(arr,75)
IQR=q3-q1
print("Interquartile Range (IQR):",IQR)

Interquartile Range (IQR): 18.0


In [14]:
uf=q3+1.5*IQR
lf=q1-1.5*IQR
l=[]
for i in arr:
    if i>=lf and i<=uf:
        l.append(i)
    arr2=np.array(l)

print(arr)
print(arr2)

[  2   3   4   6   7   8   9  12  13  16  17  23  25  27  34  37 201]
[ 2  3  4  6  7  8  9 12 13 16 17 23 25 27 34 37]


To print boxplot

In [ ]:
import seaborn as sns
sns.boxplot(x=arr)
sns.boxplot(x=arr2)