In [32]:
import numpy as np

1D array

In [33]:
arr=np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


2D Array

In [34]:
arra=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arra)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


List VS numpy Array

In [35]:
py_list=[1,2,3]
print("python list multipication",py_list*3)

python list multipication [1, 2, 3, 1, 2, 3, 1, 2, 3]


calculate time

In [36]:
import time
start=time.time()
pylist=[i*2 for i in range(100000)]
print("\n list operation time:",time.time()-start)
start=time.time()
np_array=np.arange(1000000)*2
print("\n Numpy Operation time:",time.time()-start)


 list operation time: 0.008327007293701172

 Numpy Operation time: 0.014718294143676758
